### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Test with latest `develop` version of `http`.

Does everything that's documented.

### CODE REVIEW

**Comment by thecoshman** [comment]
the '-h' help is describing 'url' all wrong, "Directory to host. Default: current working directory".
attempting to contact something like "google.com" result in an endless loop of 
> Contents of http://google.com/:
> <Couldn't parse server response: expected value at line 1 column 1...>

I suspect you are doing something to the console output and changing how the console shows where you current cursor is.

**Comment by nabijaczleweli** [comment]
Nay, "expected value at line 1 column 1" is an error from the JSON parser.

**Comment by thecoshman** [comment]
Sorry, really misleading what I was saying. One issue was the endless loop if I tried to go to google.com, the other issues was the console was being messed up.

**Comment by nabijaczleweli** [comment]
Fixed the infinite loop. As for the "console [...] being messed up" I have no idea what yer on about.

**Comment by thecoshman** [comment]
I'll open an issue for the console thing... it's wasn't a big deal, and could have been down something on my machine. I'll have to try a few other setups to see what is causing what I was seeing.

**Review by thecoshman — APPROVED** [review]

**Pull request merged**
